// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQ69Kjg83vjDxXRhC3M449wv-DVIsTkI',
    appId: '1:351738778131:web:aa3e60df9a9c63aca8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    authDomain: 'cleanarchi-f18e6.firebaseapp.com',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
    measurementId: 'G-F5L4JVTEKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5MrKDP6BiXC_GtYr2Dw6NnM8AQ4_DlY',
    appId: '1:351738778131:android:093e53922dbea722a8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuq-Nq07peqY2C9-pFLKmnzf8BmQ62ig',
    appId: '1:351738778131:ios:199c9f253e47ae93a8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
    iosClientId: '351738778131-niv9ckkermmv01mcvn3o2l7uf5r4jq04.apps.googleusercontent.com',
    iosBundleId: 'com.pearlorginsation.cleanarchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuq-Nq07peqY2C9-pFLKmnzf8BmQ62ig',
    appId: '1:351738778131:ios:44b0d3d8868b0572a8e5e6',
    messagingSenderId: '351738778131',
    projectId: 'cleanarchi-f18e6',
    storageBucket: 'cleanarchi-f18e6.appspot.com',
    iosClientId: '351738778131-vobspknpgp7o933mue4c0h8cbak1h04d.apps.googleusercontent.com',
    iosBundleId: 'com.pearlorginsation.cleanarchi.RunnerTests',
  );
}
